server:
  port: 8080
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: com.work.pamper.entity
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://db:3306/pamper?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Zdm@123}