server:
  port: 8080
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: com.work.pamper.mybatis.entity
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pamper?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root